import random
num1 = random.randint(1, 100)
num2 = random.randint(1, 100)
num3 = random.randint(1, 100)
num4 = random.randint(1, 100)
num5 = random.randint(1, 100)
tupla = (num1, num2, num3, num4, num5)
print(tupla)
print("O maior valor é:", max(tupla),"e o menor é:", min(tupla))
print("A posição do maior elemento é:", tupla.index(max(tupla)),"e a do menor é:", tupla.index(min(tupla)))
